import type { Metadata } from "next";
import { Google_Sans } from "next/font/google";
import type { ReactNode } from "react";

import "@/assets/styles/globals.css";

const googleSans = Google_Sans({
	variable: "--font-google-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang="en">
			<body className={`${googleSans.variable} antialiased`}>{children}</body>
		</html>
	);
}
